apiVersion: apps/v1        # API version for deployments
kind: Deployment           # Kind specifies this is a Deployment
metadata:
  name: my-first-deployment
  labels:
    app: nginx

spec:
  replicas: 3              # Number of pod copies
  selector:
    matchLabels:
      app: nginx           # Connects deployment to the correct pods
  
  template:
    metadata:
      labels:
        app: nginx         # Labels for the pods themselves
    
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80



