apiVersion: v1
kind: Pod
metadata:
  name: secret-demo-pod
spec: 
  containers:
  - name: secret-demo-container
    image: nginx

    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: password 

    volumeMounts:
    - name: secrets-volume
      mountPath: /etc/secrets
      readOnly: true

  volumes:
  - name: secrets-volume 
    secret:
      secretName: my-secret
